server:
  port: 7002

spring:
  application:
    name: lucky-consul-client # 服务名称
  cloud:
    consul:
      host: localhost        # Consul 服务器地址
      port: 8500             # 默认端口
      discovery:
        service-name: ${spring.application.name}  # 使用应用名作为注册名
        health-check-path: /actuator/health       # 健康检查路径
        health-check-interval: 10s               # 健康检查间隔
lucky:
  http-server:
    common:
#      url: http://localhost:7005
      service-name: lucky-consul-server
  http-client:
    logger:
      packages:
        - io.github.lucklike.discovery.consul.api
        - io.github.lucklike.common.api

