server:
  port: 8002

spring:
  application:
    name: lucky-zookeeper-client
  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181
      discovery:
        enabled: true
        register: true

lucky:
  http-server:
    common:
#      url: http://localhost:8001
      service-name: lucky-zookeeper-server

  http-client:
    logger:
      packages:
      - io.github.lucklike.discivery.zookeeper.api
      - io.github.lucklike.common.api
