server:
  port: 9992

spring:
  application:
    name: lucky-nacos-client
  cloud:
    nacos:
      discovery:
        group: lucky-group
        namespace: lucky
      server-addr: 127.0.0.1:8848

lucky:
  http-client:
    logger:
      packages: io.github.lucklike.discovery.nacos.server.api