server:
  port: 8881  # 微服务端口

spring:
  application:
    name: lucky-eureka-server  # 微服务名称

eureka:
  client:
    service-url:
      # Eureka Server 地址
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true  # 让其他服务可以直接通过 IP 访问
    lease-renewal-interval-in-seconds: 10  # 发送心跳间隔（默认 30s）
    lease-expiration-duration-in-seconds: 30  # 失效时间（默认 90s）
