server:
  port: 7001

spring:
  application:
    name: lucky-consul-server # 服务名称
  cloud:
    consul:
      host: localhost        # Consul 服务器地址
      port: 8500             # 默认端口
      discovery:
        service-name: ${spring.application.name}  # 使用应用名作为注册名
        health-check-path: /actuator/health       # 健康检查路径
        health-check-interval: 10s               # 健康检查间隔

