spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/lucy-db
      username: root
      password: ygrmytlFK7075
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000
