io.github.lucklike.luckyclient.api.spark.SparkOpenApi:
  url: https://spark-api-open.xf-yun.com/{version}/chat
  method: POST
  spring-el-import:
    root:
      appId: ca865d28
    pack:
      - java.util
      - cn.hutool.crypto.digest
  path:
    version: v1


  #------------------------------------------【SSE】讯飞火星-大模型问答------------------------------------------------#
  completions:
    sse: /completions
    reed-timeout: 30000
    spring-el-import:
      root:
        appKey: dfa83ce6cd5f556d7b2a0da18d6c4060
        APISecret: ZWM2ZTA0Y2ExNDczNDA3ZThiMjYyMDI5
    header:
      Authorization: "Bearer #{appKey}:#{APISecret}"
    body:
      json:
        model: generalv3
        stream: true
        messages:
          - role: user
            content: "#{content}"
    sse-listener:
      class-name: io.github.lucklike.luckyclient.api.spark.SparkCompletionsEventListener

  #------------------------------------------讯飞火星-身份证识别------------------------------------------------#
  idCardOcr:
    url: https://webapi.xfyun.cn/v1/service/v1/ocr/idcard
    spring-el-import:
      root:
        appKey: e1431c7b9abea73727f3d01f534c4bd2
        currTime: "#{(new Date().getTime() / 1000).toString()}"
        param: >-
          {
            "engine_type":"idcard",
          	"head_portrait": "0",
            "crop_image": "0"
          }
        base64Param: "#{#base64(param)}"
    header:
      X-Appid: "#{appId}"
      X-CurTime: "#{currTime}"
      X-Param: "#{base64Param}"
      X-CheckSum: "#{T(DigestUtil).md5Hex(appKey + currTime + base64Param)}"
    form:
      image: "#{#base64(#resource(path))}"
#    interceptor:
#      class-name: io.github.lucklike.luckyclient.api.spark.SparkOpenApi$IdCardOcrInterceptor