io.github.lucklike.luckyclient.api.spark.SparkOpenApi:
  method: POST
  spring-el-import:
    root:
      appId: "#{#sm4('80a79d2a48ae6f9e2f74a0765e64e5a9')}"
      completions_app_key: "#{#sm4('bb42a310a6e1522f93c6d9415a86ac2ba58eb345a17afb49275639fc34e35c5980097781df3b0e52d5b9af3b2f1efdf4')}"
      completions_api_secret: "#{#sm4('d0a1ec7014d601a52d5e489278d91988c01cfae00a26df03bbd0359933a2d3cb80097781df3b0e52d5b9af3b2f1efdf4')}"
      id_card_app_key: "#{#sm4('2622b4fe9e1a6ba9c5038c2c4c9f1648bf24263f2a407392ccb4bdbdd542659980097781df3b0e52d5b9af3b2f1efdf4')}"
    fun:
      - io.github.lucklike.luckyclient.api.transdog.FanYiGouFunction
    pack:
      - java.util
  resp-convert:
    condition:
      - assertion: "#{$status$ != 200}"
        exception: "讯飞火星API调用失败，异常的HTTP状态码：#{$status$}"


  #------------------------------------------【SSE】讯飞火星-大模型问答------------------------------------------------#
  completions:
    sse: https://spark-api-open.xf-yun.com/v1/chat/completions
    reed-timeout: 30000
    header:
      Authorization: "Bearer #{completions_app_key}:#{completions_api_secret}"
    body:
      json:
        model: generalv3
        stream: true
        messages:
          - role: user
            content: "#{content}"
    sse-listener:
      class-name: io.github.lucklike.luckyclient.api.spark.SparkCompletionsEventListener

  #------------------------------------------讯飞火星-身份证识别------------------------------------------------#
  idCardOcr:
    url: https://webapi.xfyun.cn/v1/service/v1/ocr/idcard
    spring-el-import:
      root:
        currTime: "#{(new Date().getTime() / 1000).toString()}"
        param: >-
          {
            "engine_type":"idcard",
          	"head_portrait": "0",
            "crop_image": "0"
          }
        base64Param: "#{#base64(param)}"
    header:
      X-Appid: "#{appId}"
      X-CurTime: "#{currTime}"
      X-Param: "#{base64Param}"
      X-CheckSum: "#{#md5(id_card_app_key + currTime + base64Param)}"
    form:
      image: "#{#base64(#resource(path))}"
    resp-convert:
      result: "#{$body$.data}"
      condition:
        - assertion: "#{$body$.code != '0'}"
          exception: "【身份证识别】讯飞火星API调用失败，异常的CODE状态码：[#{$body$.code}]: #{$body$.error_msg}"

  imageGenerate:
    spring-el-import:
      root:
        url: https://spark-api.cn-huabei-1.xf-yun.com/v2.1/tti
        APIKey: dfa83ce6cd5f556d7b2a0da18d6c4060
        APISecret: ZWM2ZTA0Y2ExNDczNDA3ZThiMjYyMDI5
      fun:
        - io.github.lucklike.luckyclient.api.spark.AuthUtils
    url: "#{#getUrl(url, 'POST', APISecret, APIKey)}"
    method: POST
    body:
      json:
        header:
          app_id: "#{appId}"
        parameter:
          chat:
            domain: general,
            width: 512,
            height: 512
        payload:
          message:
            text:
              - role: user
                content: "#{content}"



