io.github.lucklike.luckyclient.api.spark.SparkOpenApi:
  method: POST
  spring-el-import:
    root:
      appId: ${spark.appId}
      #大模型
      completion:
        APIKey: ${spark.completions.APIKey}
        APISecret: ${spark.completions.APISecret}
      #身份证识别
      idCard:
        APIKey: ${spark.idCard.APIKey}
      #图像生成
      image:
        APIKey: ${spark.imageGenerate.APIKey}
        APISecret: ${spark.imageGenerate.APISecret}
      list:
        - APIKey: 1234
          APISecret: ${spark.imageGenerate.APISecret}
        - APIKey: 5678
          APISecret: ${spark.imageGenerate.APIKey}
    fun:
      - io.github.lucklike.luckyclient.api.transdog.FanYiGouFunction
      - io.github.lucklike.luckyclient.api.spark.AuthUtils
    pack:
      - java.util
  resp-convert:
    condition:
      - assertion: "#{$status$ != 200}"
        exception: "讯飞火星API调用失败，异常的HTTP状态码[#{$status$}]: #{$body$.header.message}"


  #------------------------------------------【SSE】讯飞火星-大模型问答------------------------------------------------#
  completions:
    sse: https://spark-api-open.xf-yun.com/v1/chat/completions
    header:
      Authorization: "Bearer #{completion.APIKey}:#{completion.APISecret}"
    body:
      json:
        model: generalv3
        stream: true
        messages:
          - role: user
            content: "#{content}"
    sse-listener:
      class-name: io.github.lucklike.luckyclient.api.spark.SparkCompletionsEventListener

  #------------------------------------------讯飞火星-身份证识别------------------------------------------------#
  idCardOcr:
    url: https://webapi.xfyun.cn/v1/service/v1/ocr/idcard
    spring-el-import:
      root:
        currTime: "#{(new Date().getTime() / 1000).toString()}"
        param: >-
          {
            "engine_type":"idcard",
          	"head_portrait": "0",
            "crop_image": "0"
          }
        base64Param: "#{#base64(param)}"
    header:
      X-Appid: "#{appId}"
      X-CurTime: "#{currTime}"
      X-Param: "#{base64Param}"
      X-CheckSum: "#{#md5(idCard.APIKey + currTime + base64Param)}"
    form:
      image: "#{#base64(#resource(path))}"
    resp-convert:
      result: "#{$body$.data}"
      condition:
        - assertion: "#{$body$.code != '0'}"
          exception: "【身份证识别】讯飞火星API调用失败，异常的CODE状态码：[#{$body$.code}]: #{$body$.error_msg}"

  #------------------------------------------讯飞火星-图片生成------------------------------------------------#
  imageGenerate:
    spring-el-import:
      root:
        url: https://spark-api.cn-huabei-1.xf-yun.com/v2.1/tti
    url: "#{#getAuthUrl(url, image.APIKey, image.APISecret)}"
    method: POST
    body:
      json:
        header:
          app_id: "#{appId}"
        parameter:
          chat:
            domain: general
            width: 512
            height: 512
        payload:
          message:
            text:
              - role: user
                content: "#{content}"
    resp-convert:
      condition:
        - assertion: "#{$body$.header.code != 0}"
          exception: "【图片生成】讯飞火星API调用失败，异常的CODE状态码：[#{$body$.header.code}]: #{$body$.header.message}"
      result: "#{$body$.payload.choices.text[0].content}"



